name: Create tag on release PR merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  create-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

    #   - name: Extract version from commit message
    #     id: version
    #     shell: bash
    #     run: |
    #       msg="$(git log -1 --pretty=%B)"
    #       echo "Commit message:"
    #       echo "$msg"

    #       if [[ "$msg" =~ release:\ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
    #         version="v${BASH_REMATCH[1]}"
    #         echo "version=$version" >> $GITHUB_OUTPUT
    #       else
    #         echo "No release version found, skip"
    #         exit 0
    #       fi

      - name: Extract release version
        id: version
        if: github.event.pull_request.merged == true
        shell: bash
        run: |
          # VERSION=$(echo "${{ github.event.pull_request.title }}" \
          #   | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          # echo "version=$VERSION" >> $GITHUB_OUTPUT

          # title="${{ github.event.pull_request.title }}"
          VERSION=$(echo "${{ github.event.pull_request.title }}" \
            | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ "$VERSION" != "" ]]; then
            # echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Check tag exists
        id: check
        shell: bash
        run: |
          if git rev-parse "${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.version.outputs.version != ''
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      # - name: Call release workflow
      #   if: steps.version.outputs.version != ''
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       await github.rest.actions.createWorkflowDispatch({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         workflow_id: "release.yml",
      #         ref: "main",
      #         inputs: {
      #           version: "${{ steps.version.outputs.version }}"
      #         }
      #       })

      # - name: Call reusable workflow
      #   if: steps.version.outputs.is_release == 'true'
      #   uses: ./.github/workflows/release.yml@main  # 注意这里的写法
      #   with:
      #     version: ${{ steps.version.outputs.version }}
          # tag_name: ${{ steps.version.outputs.tag_name }}
          # pr_number: ${{ github.event.pull_request.number }}
          # pr_title: ${{ github.event.pull_request.title }}
        # secrets: inherit 